---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

library(ggplot2)
library(scales)
library(Hmisc)
## Loading and preprocessing the data
dataDir='/Users/asad/R/datasciencecoursera/RepResearch/RepData_PeerAssessment1/data/activity.csv'
data=read.csv(dataDir)


## What is mean total number of steps taken per day?

## 1. The total number of steps taken per day calculation
total<-tapply(data$steps,as.factor(data$date),sum,na.rm=TRUE)

## 2. Histogram of the total number of steps taken each day

qplot(total, xlab='Total steps per day', ylab='Frequency')

## 3.Calculation and report the mean and median of the total number of steps taken per day
mean_steps<-mean(total)
median_steps<-median(total)
print(mean_steps)
print(median_steps)
## What is the average daily activity pattern?

## 1. Make a time series plot (i.e. ðšðš¢ðš™ðšŽ = "ðš•") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
aggdata <-aggregate(data$steps, by=list(data$interval), 
  FUN=mean, na.rm=TRUE)
ggplot(data = aggdata, aes(x=Group.1, y=x)) + 
  geom_line()+
  labs( colour = "City",
        x = "5 minutes interval",
        y = "average steps accross all day",
        title = "Time series plot of the 5-minute interval and the average number of steps taken")

## 2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
 max_steps<-which.max(aggdata$x)
max_avg_step<-aggdata[max_steps,]$Group.1
timeMostSteps <-  gsub("([0-9]{1,2})([0-9]{2})", "\\1:\\2",max_avg_step)
* timeMostSteps
## Imputing missing values

#### Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with ð™½ð™°s)
missing_row<-sum(is.na(data$steps))
print(missing_row)
#### Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
#### Create a new dataset that is equal to the original dataset but with the missing data filled in.
copied_data<-data
copied_data$steps<-impute(data$steps,fun=mean)
#### Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

## 1. The total number of steps taken per day calculation
total<-tapply(copied_data$steps,as.factor(copied_data$date),sum,na.rm=TRUE)

## 2. Histogram of the total number of steps taken each day

qplot(total, xlab='Total steps per day', ylab='Frequency')

## 3.Calculation and report the mean and median of the total number of steps taken per day
mean_steps<-mean(total)
median_steps<-median(total)
print(mean_steps)
print(median_steps)
## Are there differences in activity patterns between weekdays and weekends?
copied_data$dateType<-as.factor(ifelse(weekdays(as.Date(copied_data$date))%in% c("Saturday","Sunday"),"weekend","weeekday"))
# ploat
averagedActivityDataImputed <- aggregate(steps ~ interval + dateType, data=copied_data, mean)
ggplot(averagedActivityDataImputed, aes(interval, steps)) + 
    geom_line() + 
    facet_grid(dateType ~ .) +
    xlab("5-minute interval") + 
    ylab("avarage number of steps")